"""Initial PostgreSQL schema

Revision ID: af156c478b3f
Revises: 
Create Date: 2026-08-11 11:37:54.981156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af156c478b3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_type', sa.String(length=50), nullable=True),
    sa.Column('heygen_avatar_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_talking_photo_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_avatar_group_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_voice_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctors_heygen_avatar_group_id'), 'doctors', ['heygen_avatar_group_id'], unique=False)
    op.create_index(op.f('ix_doctors_heygen_avatar_id'), 'doctors', ['heygen_avatar_id'], unique=False)
    op.create_index(op.f('ix_doctors_heygen_talking_photo_id'), 'doctors', ['heygen_talking_photo_id'], unique=False)
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('heygen_video_id', sa.String(length=255), nullable=True),
    sa.Column('video_type', sa.String(length=50), nullable=True),
    sa.Column('avatar_type', sa.String(length=50), nullable=False),
    sa.Column('heygen_avatar_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_talking_photo_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_avatar_group_id', sa.String(length=255), nullable=True),
    sa.Column('heygen_voice_id', sa.String(length=255), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_doctor_id'), 'videos', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_videos_heygen_video_id'), 'videos', ['heygen_video_id'], unique=True)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=True)
    op.create_table('public_video_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_id', sa.String(length=50), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=False),
    sa.Column('qr_image', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_video_shares_doctor_id'), 'public_video_shares', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_public_video_shares_public_token'), 'public_video_shares', ['public_token'], unique=True)
    op.create_index(op.f('ix_public_video_shares_qr_id'), 'public_video_shares', ['qr_id'], unique=True)
    op.create_index(op.f('ix_public_video_shares_video_id'), 'public_video_shares', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_video_shares_video_id'), table_name='public_video_shares')
    op.drop_index(op.f('ix_public_video_shares_qr_id'), table_name='public_video_shares')
    op.drop_index(op.f('ix_public_video_shares_public_token'), table_name='public_video_shares')
    op.drop_index(op.f('ix_public_video_shares_doctor_id'), table_name='public_video_shares')
    op.drop_table('public_video_shares')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_heygen_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_doctor_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_heygen_talking_photo_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_heygen_avatar_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_heygen_avatar_group_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
